[package]
name = "unionfind"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
rand = { version = "0.9.0", features = [] }
uuid = { version = "1.16.0", features = ["v4"] }

[[example]]
name = "students"
path = "examples/bplustree/students/main.rs"